# Generated by Django 5.2 on 2025-05-16 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_number', models.CharField(blank=True, help_text='Organisasjonsnummer må være unikt', max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(help_text='Brukeren som er admin for denne bedriften', on_delete=django.db.models.deletion.CASCADE, related_name='admin_businesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
