# Generated by Django 5.2 on 2025-05-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, help_text='Gateadresse til bedriften', max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='business',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Navn på hovedkontakt for bedriften', max_length=128, null=True, verbose_name='Kontaktperson'),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, help_text='Kontakttelefon for bedriften', max_length=32, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='business',
            name='social_media',
            field=models.JSONField(blank=True, help_text='Lenker til Facebook, Instagram, osv.', null=True, verbose_name='Sosiale medier'),
        ),
    ]
