# Generated by Django 5.2 on 2025-05-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='business',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
