# Generated by Django 5.2 on 2025-05-12 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_city_business_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='admin',
            field=models.ForeignKey(default=11, help_text='Brukeren som er admin for denne bedriften', on_delete=django.db.models.deletion.CASCADE, related_name='admin_businesses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
