# Generated by Django 5.2 on 2025-05-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_address_business_contact_person_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bedrift', 'verbose_name_plural': 'Bedrifter'},
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, help_text='Street address of the business', max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='business',
            name='admin',
            field=models.ForeignKey(help_text='User who is the admin for this business', on_delete=django.db.models.deletion.CASCADE, related_name='admin_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='business',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Name of the main contact for the business', max_length=128, null=True, verbose_name='Contact Person'),
        ),
        migrations.AlterField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='organization_number',
            field=models.CharField(blank=True, db_index=True, help_text='Organization number must be unique', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone for the business', max_length=32, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='business',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='social_media',
            field=models.JSONField(blank=True, help_text='Links to Facebook, Instagram, etc.', null=True, verbose_name='Social Media'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['name', 'city'], name='businesses__name_9d9557_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['created_at'], name='businesses__created_34b472_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['admin'], name='businesses__admin_i_5eaaea_idx'),
        ),
    ]
