# Generated by Django 5.2 on 2025-05-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_alter_business_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='organization_number',
            field=models.CharField(blank=True, help_text='Organisasjonsnummer må være unikt', max_length=20, null=True, unique=True),
        ),
    ]
