# Generated by Django 5.2 on 2025-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '000X_remove_is_member_is_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(help_text='Navn på selskapet.', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(help_text='Bedriftens e-postadresse.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='organization_number',
            field=models.CharField(help_text='Organisasjonsnummer.', max_length=20, unique=True),
        ),
    ]
