# Generated by Django 5.2 on 2025-05-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text="Member's city for location-based giveaways", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this profile was created'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text="Member's profile picture", null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(help_text='The user this member profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, db_index=True, help_text="User's city/location.", max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Unique email address for login.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image for the user.', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddIndex(
            model_name='memberprofile',
            index=models.Index(fields=['user', 'city'], name='accounts_me_user_id_bea63e_idx'),
        ),
    ]
