# Generated by Django 5.2 on 2025-05-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_alter_company_company_name_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Adresse til bedriften.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Poststed/by.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='Fornavn på kontaktperson.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Etternavn på kontaktperson.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, default='', help_text='Postnummer.', max_length=10, null=True),
        ),
    ]
