# Generated by Django 5.2 on 2025-05-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profilbilde for brukeren.', null=True, upload_to='profile_pics/'),
        ),
    ]
