# Generated by Django 5.2 on 2025-05-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='prize_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Premieverdi'),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='signup_options',
            field=models.JSONField(blank=True, null=True, verbose_name='Svaralternativer (maks 4)'),
        ),
        migrations.AddField(
            model_name='giveaway',
            name='signup_question',
            field=models.CharField(blank=True, max_length=255, verbose_name='Påmeldingsspørsmål'),
        ),
    ]
