# Generated by Django 5.2 on 2025-05-22 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_business_options_alter_business_address_and_more'),
        ('giveaways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-entered_at'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='giveaway',
            options={'ordering': ['-created_at'], 'verbose_name': 'Giveaway', 'verbose_name_plural': 'Giveaways'},
        ),
        migrations.AlterModelOptions(
            name='winner',
            options={'ordering': ['-selected_at'], 'verbose_name': 'Winner', 'verbose_name_plural': 'Winners'},
        ),
        migrations.AddField(
            model_name='winner',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='answer',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entered_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user_location_city',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='end_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='prize_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prize Value'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='signup_options',
            field=models.JSONField(blank=True, null=True, verbose_name='Answer Options (max 4)'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='signup_question',
            field=models.CharField(blank=True, max_length=255, verbose_name='Signup Question'),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='start_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='winner',
            name='selected_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giveaway_wins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['giveaway', 'answer'], name='giveaways_e_giveawa_75ccd1_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user', 'entered_at'], name='giveaways_e_user_id_e30a46_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['user_location_city'], name='giveaways_e_user_lo_dccf73_idx'),
        ),
        migrations.AddIndex(
            model_name='giveaway',
            index=models.Index(fields=['business', 'is_active'], name='giveaways_g_busines_3b09b1_idx'),
        ),
        migrations.AddIndex(
            model_name='giveaway',
            index=models.Index(fields=['start_date', 'end_date'], name='giveaways_g_start_d_b96881_idx'),
        ),
        migrations.AddIndex(
            model_name='giveaway',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='giveaways_g_is_acti_74d076_idx'),
        ),
        migrations.AddIndex(
            model_name='winner',
            index=models.Index(fields=['user', 'selected_at'], name='giveaways_w_user_id_0c1407_idx'),
        ),
        migrations.AddIndex(
            model_name='winner',
            index=models.Index(fields=['notification_sent'], name='giveaways_w_notific_4e47d5_idx'),
        ),
    ]
