# Generated by Django 5.2 on 2025-05-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0002_alter_entry_options_alter_giveaway_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='notification_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
