# Generated by Django 5.2 on 2025-05-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0002_giveaway_prize_value_giveaway_signup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='user_location_city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
